### ISSUE TITLE
Travis integration

### ISSUE THREAD

**Issue by vnegrisolo** [camaral/erdbeere#4]
https://travis-ci.org/

**Comment by camaral** [comment]
@vnegrisolo Do you know why Travis is not accepting my Gemfile? It complains about the Ruby's new hash syntax.

```
Gemfile syntax error on line 11: syntax error, unexpected ':'
gem 'rails_12factor', group: :production
                           ^
```

**Comment by vnegrisolo** [comment]
I checked your last build and the failure is related to the ruby version: https://travis-ci.org/camaral/erdbeere/jobs/66835403

Probably because of the way you declared:
```yaml
rvm:
  - jruby-19mode # JRuby in 1.9 mode
```

And in Gem file: `ruby '1.9.3'`

**Comment by camaral** [comment]
I was forcing the JRuby version and configured Travis to run more than version. Now I removed it and it works. 
Still Travis is not accepting the new hash syntax, so I changed to the old (with =>).
Anyway, I will configure the script to initialize the database and hopefully I can close the issue.

In your option, is this a good travis config file: https://gist.github.com/kcampos/4126187

Thanks again, bro!

**Comment by vnegrisolo** [comment]
@camaral the new hash syntax `key: value` are available after 1.9.0. Before that was `:key => value`

**Comment by vnegrisolo** [comment]
About this conf file for travis seems really good. I never worked configuring database in travis. I will have to do very soon, so it will be a very nice start :+1:

**Comment by camaral** [comment]
Now it is running \o/
Tks, Coto!

**Comment by vnegrisolo** [comment]
:+1:
